apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::207567759296:user/preye_aws
      username: preye_aws
      groups:
        - eks-admins
